// <auto-generated />
using Eshop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Shop.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250730182645_productdata")]
    partial class productdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            UserID = 1
                        },
                        new
                        {
                            CartID = 2,
                            UserID = 2
                        },
                        new
                        {
                            CartID = 3,
                            UserID = 3
                        },
                        new
                        {
                            CartID = 4,
                            UserID = 4
                        },
                        new
                        {
                            CartID = 5,
                            UserID = 5
                        });
                });

            modelBuilder.Entity("CartProduct", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartProducts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            ProductID = 1,
                            Quantity = 2
                        },
                        new
                        {
                            CartID = 1,
                            ProductID = 3,
                            Quantity = 1
                        },
                        new
                        {
                            CartID = 2,
                            ProductID = 2,
                            Quantity = 5
                        },
                        new
                        {
                            CartID = 2,
                            ProductID = 4,
                            Quantity = 3
                        },
                        new
                        {
                            CartID = 3,
                            ProductID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            CartID = 3,
                            ProductID = 5,
                            Quantity = 2
                        },
                        new
                        {
                            CartID = 4,
                            ProductID = 2,
                            Quantity = 1
                        },
                        new
                        {
                            CartID = 5,
                            ProductID = 3,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("Eshop.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Name = "Laptop",
                            Price = 1200.00m,
                            StockLevel = 10
                        },
                        new
                        {
                            ProductID = 2,
                            Name = "Phone",
                            Price = 800.00m,
                            StockLevel = 15
                        },
                        new
                        {
                            ProductID = 3,
                            Name = "Mouse",
                            Price = 25.00m,
                            StockLevel = 50
                        },
                        new
                        {
                            ProductID = 4,
                            Name = "Keyboard",
                            Price = 45.00m,
                            StockLevel = 30
                        },
                        new
                        {
                            ProductID = 5,
                            Name = "Monitor",
                            Price = 200.00m,
                            StockLevel = 20
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "ali@example.com",
                            PasswordHash = "hashedpass1"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "sara@example.com",
                            PasswordHash = "hashedpass2"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "kareem@example.com",
                            PasswordHash = "hashedpass3"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "laila@example.com",
                            PasswordHash = "hashedpass4"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "omar@example.com",
                            PasswordHash = "hashedpass5"
                        });
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Cart", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartProduct", b =>
                {
                    b.HasOne("Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eshop.Product", "Product")
                        .WithMany("CartProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("Eshop.Product", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
